name: Latest BLOGS
on:
  schedule:
    # Runs every 5 minutes
    - cron: "*/100 * * * *"
  workflow_dispatch:
jobs:
  update-readme-with-stack-overflow:
    name: Update this repo's README with latest activity from StackOverflow
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          comment_tag_name: "BLOGS"
          commit_message: "Updated readme with the latest blog posts"
          feed_list: https://medium.com/feed/@abhi08as.as,https://abhiswain97.github.io/blog/feed"
